# type: ignore
import numpy as np

from firm_ce.common.typing import float64, unicode_type
from firm_ce.optimisation.single_time import evaluate_vectorised_xs
from firm_ce.system.components import Fleet_InstanceType
from firm_ce.system.parameters import ScenarioParameters_InstanceType
from firm_ce.system.topology import Network_InstanceType


class MGAObjective:
    """
    A wrapper class that binds the static system state to the objective function
    interface required by the MGA algorithm.

    It adapts the MGA population format (N samples, D features) to the
    vectorised evaluation format (D features, N samples) used by firm_ce.
    """

    def __init__(
        self,
        static: ScenarioParameters_InstanceType,
        fleet: Fleet_InstanceType,
        network: Network_InstanceType,
        balancing_type: unicode_type,
        fixed_costs_threshold: float64,
    ):
        self.static = static
        self.fleet = fleet
        self.network = network
        self.balancing_type = balancing_type
        self.fixed_costs_threshold = fixed_costs_threshold

    def __call__(self, values_array: np.ndarray) -> np.ndarray:
        """
        Evaluate the objective function for a population of solutions.

        Parameters:
        -----------
        values_array (np.ndarray): A 2D array of shape (pop_size, dimensions) containing
            the population of candidate solutions generated by MGA.

        Returns:
        --------
        np.ndarray: A 1D array of shape (pop_size,) containing the fitness/cost
            values for each candidate.
        """
        return evaluate_vectorised_xs(
            values_array.T,
            self.static,
            self.fleet,
            self.network,
            self.balancing_type,
            self.fixed_costs_threshold,
        )[1:, :]  # columns: cost, penalties
